### ISSUE TITLE
Add Support For Hooks

### ISSUE THREAD

**Issue by nlordell** [cowprotocol/arak#36]
This issue captures the work to add support for "hook" configurations. The loose idea is to be able to specify SQL by file or code that runs on updates to the DB. This allows the indexing service to additionally run custom queries within the same transaction as the one where events are indexed.

The current idea would be to add:
```toml
[[hook]]
query = """
-- some SQL query
"""
on = "finalized"
init = false # disable running the hook on initialization when syncing historical 

[[hook]]
file = "path/to/query.sql"
# defaults to run on initialization when updating of historical data and on every block thereafter
```

### Open Questions

This can potentially cause indexing to fail (if there is a bug in the user-specified SQL for example), or in general things to not work as expected. Is this a good idea?
