### ISSUE TITLE
Crashing Inserting Postgres Large Number

### ISSUE THREAD

**Issue by nlordell** [cowprotocol/arak#46]
`arak` is crashing with:

> Invalid decimal: overflow from too many digits

<details><summary>Configuration:</summary>

```toml
ethrpc = "${ethrpc}"

[database.postgres]
connection = "${database}"

[indexer]
page-size = 500
poll-interval = 0.1

[[event]]
name = "uniswapv2_PairCreated"
start = 10000835
contract = "0x5C69bEe701ef814a2B6a3EDD4B1652CB9cc5aA6f"
signature = "event PairCreated(address indexed token0, address indexed token1, address pair, uint)"

[[event]]
name = "uniswapv2_Sync"
start = 10000835
contract = "*"
signature = "event Sync(uint112 reserve0, uint112 reserve1)"
```

</details>

This is happening with logs somewhere in between 10164335 and 10164834 on mainnet
